# Generated by Django 6.0.3 on 2026-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='saving_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
    ]
