# Generated by Django 6.0.3 on 2026-03-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_register_saving_total_alter_loan_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='saving_total',
        ),
        migrations.AddField(
            model_name='register',
            name='saving',
            field=models.FloatField(default=0),
        ),
    ]
