# Generated by Django 6.0.3 on 2026-03-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_register_saving_total_register_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='saving',
        ),
        migrations.AddField(
            model_name='register',
            name='saving_total',
            field=models.FloatField(default=0),
        ),
    ]
