# Generated by Django 6.0.3 on 2026-03-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_register_saving_register_saving_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='saving_total',
        ),
        migrations.AddField(
            model_name='register',
            name='savings_total',
            field=models.FloatField(default=0),
        ),
    ]
