# Generated by Django 6.0.3 on 2026-03-12 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_register_saving_total_register_savings_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shgname', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('expected_contribution', models.FloatField(default=100)),
                ('paid_amount', models.FloatField(default=0)),
                ('personal_loan_taken', models.FloatField(default=0)),
                ('loan_paid', models.FloatField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.register')),
            ],
        ),
    ]
