# Generated by Django 6.0.3 on 2026-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_monthlyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default='Personal', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='member_name',
            field=models.CharField(default='Group Loan', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='shgname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
