# Generated by Django 6.0.3 on 2026-03-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_loan_loan_type_loan_member_name_alter_loan_shgname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyrecord',
            old_name='paid_amount',
            new_name='saving_paid',
        ),
        migrations.AddField(
            model_name='monthlyrecord',
            name='emi_paid',
            field=models.FloatField(default=0),
        ),
    ]
