# Generated by Django 6.0.3 on 2026-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_paid_amount_monthlyrecord_saving_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='register',
            name='savings_total',
        ),
        migrations.AddField(
            model_name='register',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='register',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_photos/'),
        ),
        migrations.AddField(
            model_name='register',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
