# Generated by Django 6.0.3 on 2026-03-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='subsidy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_installment',
            field=models.IntegerField(default=0),
        ),
    ]
