# Generated by Django 6.0.3 on 2026-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_loan_interest_rate_loan_subsidy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
