# Generated by Django 6.0.3 on 2026-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contact_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='type',
            field=models.CharField(choices=[('Message', 'Message'), ('Complaint', 'Complaint')], default='Message', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
