# Generated by Django 6.0.3 on 2026-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_contactmessage_type_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='type',
            field=models.CharField(choices=[('Message', 'Message'), ('Complaint', 'Complaint')], default='Complaint', max_length=20),
        ),
    ]
