# Generated by Django 6.0.3 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_loan_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.RemoveField(
            model_name='register',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='register',
            name='aadhar_photo',
        ),
        migrations.AddField(
            model_name='register',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='register',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_photos/'),
        ),
    ]
