# Generated by Django 6.0.3 on 2026-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_register_dob_register_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Left', 'Left')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
