# Generated by Django 6.0.3 on 2026-04-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_register_left_date_register_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='member_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.register'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.register'),
        ),
        migrations.AlterField(
            model_name='register',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Member', 'Member')], max_length=20),
        ),
    ]
