# Generated by Django 6.0.3 on 2026-04-17 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_loan_member_name_remove_meeting_member_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='member',
            new_name='member_name',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='member',
        ),
        migrations.AddField(
            model_name='loan',
            name='member_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.register'),
        ),
    ]
