# Generated by Django 6.0.3 on 2026-04-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_member_meeting_member_name_remove_loan_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='member_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='joined_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
