# Generated by Django 6.0.3 on 2026-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_loan_member_name_alter_meeting_member_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shgname', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
