# Generated by Django 6.0.3 on 2026-04-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_meetingschedule_delete_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='member_name',
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.register'),
        ),
    ]
