# Generated by Django 6.0.3 on 2026-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_loan_member_name_loan_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
