# Generated by Django 6.0.3 on 2026-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_register_joined_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyrecord',
            old_name='emi_paid',
            new_name='personal_emi',
        ),
        migrations.AddField(
            model_name='monthlyrecord',
            name='group_emi',
            field=models.FloatField(default=0),
        ),
    ]
