# Generated by Django 6.0.3 on 2026-04-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_emi_paid_monthlyrecord_personal_emi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='emi_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='subsidy',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_installment',
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='subvention_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_payable',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Group', 'Group'), ('Personal', 'Personal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='shgname',
            field=models.CharField(default='default_shg', max_length=100),
            preserve_default=False,
        ),
    ]
