# Generated by Django 6.0.3 on 2026-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_loan_emi_date_remove_loan_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
