# Generated by Django 6.0.3 on 2026-04-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_loan_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
