# Generated by Django 6.0.3 on 2026-04-23 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
