# Generated by Django 6.0.3 on 2026-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='emi',
            field=models.FloatField(default=0),
        ),
    ]
