# Generated by Django 6.0.3 on 2026-04-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_loan_emi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.village')),
            ],
        ),
    ]
