# Generated by Django 6.0.3 on 2026-04-29 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_shg'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='shg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
    ]
