# Generated by Django 6.0.3 on 2026-04-29 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_register_shg'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='register',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AlterUniqueTogether(
            name='shg',
            unique_together={('name', 'village')},
        ),
        migrations.RemoveField(
            model_name='register',
            name='shgname',
        ),
    ]
