# Generated by Django 6.0.3 on 2026-04-29 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_register_unique_together_alter_register_shg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='shg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='shg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AddField(
            model_name='monthlyrecord',
            name='shg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AddField(
            model_name='project',
            name='shg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
    ]
