# Generated by Django 6.0.3 on 2026-04-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_loan_shg_meetingschedule_shg_monthlyrecord_shg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='shgname',
        ),
        migrations.RemoveField(
            model_name='meetingschedule',
            name='shgname',
        ),
        migrations.RemoveField(
            model_name='monthlyrecord',
            name='shgname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shgname',
        ),
        migrations.AlterField(
            model_name='loan',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AlterField(
            model_name='monthlyrecord',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shg'),
        ),
    ]
